name: Continuous Integration

on: 
  push:
    branches:
      - '**'
    # Don't trigger CI for a tag, the commit will trigger it already.
    tags-ignore:
      - '*.*'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNETVERSION: '7.0.x'
  SOLUTION_FILE: 'NetEnhancements.sln'

jobs:
  Build_and_Test:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Setup NuGet Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
      
      - name: Setup .NET Core SDK ${{ env.DOTNETVERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNETVERSION }}

      - name: Restore
        run: dotnet restore $SOLUTION_FILE
      
      - name: Build
        run: dotnet build $SOLUTION_FILE --configuration Release --no-restore
      
      - name: Test
        run: dotnet test $SOLUTION_FILE -c Release --no-restore --no-build
