name: Publish Docs

on: 
  push:
    branches:
      - 'main'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNETVERSION: '7.0.x'
  SOLUTION_FILE: 'NetEnhancements.sln'

jobs:
  publish_docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
        
      - name: Set up .NET Core SDK ${{ env.DOTNETVERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNETVERSION }}
      
      - name: Set up docfx
        run: dotnet tool update --global docfx
        
      - name: Set up DocFxTocGenerator
        run: dotnet tool update --global DocFxTocGenerator
        
      - name: Generate TOCs for articles
        run: DocFxTocGenerator --docfolder docfx/articles --sequence --override

      - name: Compile documentation
        run: docfx docfx/docfx.json
      
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docfx/_site
          personal_token: ${{ secrets.DOCS_PUSH_KEY }}
          external_repository: NetEnhancements/netenhancements.github.io
